# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# For a deeper explanation of the caching strategy,
# see discussion in https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ .Branch }}-
            - v1-yarn-master-
            - v1-yarn-
      - run:
          name: Yarn - Install Depencendies
          command: |
            yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: All JS Packages - Test
          command: |
            yarn test:once
      - run:
          name: All JS Packages - Typecheck
          command: |
            yarn typecheck
      - run:
          name: All JS Packages - Lint
          command: |
            yarn lint
      - run:
          name: All JS Packages - Check Format
          command: |
            yarn format:ci

      - restore_cache:
          keys:
            - v1-tracker-{{ .Branch }}-
            - v1-tracker-master-
            - v1-tracker-
      - run:
          name: '@anonytics/tracker - Build'
          working_directory: ./packages/tracker
          command: |
            yarn build
      - save_cache:
          paths:
            - packages/tracker/.rts2_cache_cjs
            - packages/tracker/.rts2_cache_es
            - packages/tracker/.rts2_cache_umd
            - packages/tracker/build
          key: v1-tracker-{{ .Branch }}-{{ epoch }}

      - run:
          name: '@anonytics/tracker - Check Bundle Size'
          command: |
            yarn bundlesize

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
