# For a deeper explanation of the caching strategy,
# see discussion in https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694
version: 2.1
orbs:
  yarn: artsy/yarn@2.0.0
executors:
  node:
    docker:
      - image: circleci/node:10
jobs:
  build:
    executor: node
    steps:
      - yarn/setup
      - yarn/run-script:
          script: build
      - persist_to_workspace:
          root: .
          paths:
            - ./packages/tracker/build
  bundlesize:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - yarn/setup
      - yarn/run-script:
          script: bundlesize
workflows:
  version: 2
  test-n-build:
    jobs:
      - yarn/update-cache:
          name: update-cache
      - yarn/jest:
          name: jest
      - yarn/type-check:
          name: type-check
      - yarn/lint:
          name: lint
      - yarn/run:
          script: format:ci
          name: prettier
      - build
      - bundlesize:
          requires:
            - build
