# For a deeper explanation of the caching strategy,
# see discussion in https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694
version: 2.1
orbs:
  yarn: artsy/yarn@2.0.0
executors:
  node:
    docker:
      - image: circleci/node:10
jobs:
  build-n-bundlesize:
    executor: node
    steps:
      # yarn/run-script takes care of installing yarn dependencies, we don't want to do that twice
      - yarn/run-script:
          script: build
      - run: yarn bundlesize
workflows:
  version: 2
  update-cache:
    jobs:
      - yarn/update-cache:
          name: update-cache
  test:
    jobs:
      - yarn/jest:
          name: jest
  type-check:
    jobs:
      - yarn/type-check:
          name: type-check
  lint:
    jobs:
      - yarn/lint:
          name: lint
  prettier:
    jobs:
      - yarn/run:
          script: format:ci
          name: prettier
  alex:
    jobs:
      - yarn/run:
          script: alex
          name: prettier
  build-n-bundlesize:
    jobs:
      - build-n-bundlesize
