# For a deeper explanation of the caching strategy,
# see discussion in https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694
version: 2.1
orbs:
  yarn: artsy/yarn@2.0.0
executors:
  node:
    docker:
      - image: circleci/node:10
jobs:
  build-n-bundlesize:
    executor: node
    steps:
      - yarn/run-script:
          script: build
      - yarn/run-script:
          script: bundlesize
  bundlesize:
    executor: node
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - yarn/run-script:
          script: bundlesize --config bundlesize.config.ci.json
workflows:
  version: 2
  test-n-build:
    jobs:
      - yarn/update-cache:
          name: update-cache
      - yarn/jest:
          name: jest
      - yarn/type-check:
          name: type-check
      - yarn/lint:
          name: lint
      - yarn/run:
          script: format:ci
          name: prettier
      - build-bundlesize
      # - bundlesize:
      #     requires:
      #       - build
