# For a deeper explanation of the caching strategy,
# see discussion in https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694
version: 2.1
orbs:
  yarn: artsy/yarn@2.1.0
  codecov: codecov/codecov@1.0.5
executors:
  node:
    docker:
      - image: circleci/node:10
jobs:
  build-n-bundlesize:
    executor: node
    steps:
      # yarn/run-script takes care of installing yarn dependencies, we don't want to do that twice
      - yarn/run-script:
          script: build
      - run: yarn bundlesize
  # test-w-coverage:
  #   executor: node
  #   steps:
  #     - yarn/jest:
  #         args: --maxWorkers=4 --coverage
  #     - codecov/upload:
  #         file: ./coverage/coverage-final.json
  #     - store_artifacts:
  # path: ./coverage
workflows:
  version: 2
  all-checks-and-build:
    jobs:
      - yarn/update-cache:
          name: update-cache
      - yarn/run:
          script: alex
          name: alex
      - yarn/run:
          script: format:ci
          name: prettier
      - yarn/lint:
          name: lint
      - yarn/type-check:
          name: type-check
      - yarn/jest:
          name: jest
          args: --maxWorkers=4 --coverage
          steps:
            - codecov/upload:
                file: ./coverage/coverage-final.json
            - store_artifacts:
                path: ./coverage
      - build-n-bundlesize
